name: visistafri
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  datetime_picker_formfield: ^1.0.0
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_signin_button: ^1.1.0
  fluttertoast: ^7.1.4
  readmore: ^1.0.0
  device_preview: ^0.5.5
  


  carousel_slider: ^2.3.1
  english_words: ^3.1.3
  country_provider: ^0.0.1
  circular_profile_avatar: ^1.0.8
dev_dependencies:
  flutter_launcher_icons: "^0.7.3"
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter: 
   

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/mycover.png
    - assets/images/cover1.png
    - assets/images/Group 3.png
    - assets/images/facebook.png
    - assets/images/search.png
  
  
    - assets/images/af.JPEG
    - assets/images/kc.JPG
    - assets/images/mega.JPG
    - assets/images/vc.JPG
    - assets/images/vc2.JPG
    - assets/images/vc3.JPG
    - assets/images/vc4.JPG
    - assets/images/vc5.JPG
    - assets/images/saga.JPG
    - assets/images/cnp.JPG
    - assets/images/gf.JPG
    - assets/images/cp.JPG
    - assets/images/cp2.JPG
    - assets/images/cp3.JPG
    - assets/images/cp4.JPG
    - assets/images/cp5.JPG
    - assets/images/tr.JPG
    - assets/images/ch.JPG
    - assets/images/st.JPG
    - assets/images/ac.JPG
    - assets/images/tm.JPG
    - assets/images/rw.JPG
    - assets/images/bc.JPG
    - assets/images/pb.JPG
    - assets/images/mb.JPG
    - assets/images/wb.JPG
    - assets/images/kp.JPG
    - assets/images/kp2.JPG
    - assets/images/kp3.JPG
    - assets/images/kp4.JPG
    - assets/images/kp5.JPG
    - assets/images/Image1.PNG
    - assets/images/nyugwe.JPG

    
    
   
    - assets/images/Group 3.png
    - assets/images/b1.jpg
    - assets/images/b2.jpg
    - assets/images/b3.jpg
    - assets/images/park1.jpg
    - assets/images/park2.jpg
    - assets/images/park3.jpg
    - assets/images/l1.jpg
    - assets/images/l2.jpg
    - assets/images/l3.jpg
    - assets/images/m1.png
    - assets/images/m2.png
    - assets/images/m3.png
    - assets/images/kcc2.jpg
    - assets/images/lakekivu1.png
    - assets/images/kc.jpg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages